                         #Comprehensive Exploratory Data Analysis of IPL Dataset 2008-2023

In [13]:
#import libraries
import pandas as pd

In [5]:
#loading the dataset
df=pd.read_csv("Ipl-clean-data2008-2023.csv");

In [7]:
#printing the first 5 records
df.head()

,Unnamed: 0,season,id,name,short_name,description,home_team,away_team,toss_won,decision,...,home_playx1,away_playx1,away_key_batsman,away_key_bowler,match_days,umpire1,umpire2,tv_umpire,referee,reserve_umpire
0,4,2023.0,1359544,Royal Challengers Bangalore v Gujarat Titans,RCB v GT,"70th Match (N), Indian Premier League at Benga...",RCB,GT,GT,BOWL FIRST,...,"Virat Kohli (UKN),Faf du Plessis (UKN),Glenn M...","Wriddhiman Saha (WK),Shubman Gill (UKN),Vijay ...","Shubman Gill,Vijay Shankar","Noor Ahmad,Rashid Khan",21 May 2023 - night match (20-over match),Nitin Menon,Virender Sharma,Tapan Sharma,Javagal Srinath,VM Dhokre
1,5,2023.0,1359543,Mumbai Indians v Sunrisers Hyderabad,MI v SRH,"69th Match (D/N), Indian Premier League at Mum...",MI,SRH,MI,BOWL FIRST,...,"Ishan Kishan (WK),Rohit Sharma (UKN),Cameron G...","Vivrant Sharma (AR),Mayank Agarwal (UKN),Heinr...","Mayank Agarwal,Vivrant Sharma","Bhuvneshwar Kumar,Mayank Dagar",21 May 2023 - day/night match (20-over match),KN Ananthapadmanabhan,Rod Tucker,Rohan Pandit,Pankaj Dharmani,Parashar Joshi
2,6,2023.0,1359542,Kolkata Knight Riders v Lucknow Super Giants,KKR v LSG,"68th Match (N), Indian Premier League at Kolka...",KKR,LSG,KKR,BOWL FIRST,...,"Jason Roy (UKN),Venkatesh Iyer (AR),Nitish Ran...","Karan Sharma (AR),Quinton de Kock (WK),Prerak ...","Nicholas Pooran,Quinton de Kock","Ravi Bishnoi,Yash Thakur",20 May 2023 - night match (20-over match),Ulhas Gandhe,Jayaraman Madanagopal,Yeshwant Barde,Manu Nayyar,Mohamed Rafi
3,7,2023.0,1359541,Delhi Capitals v Chennai Super Kings,DC v CSK,"67th Match (D/N), Indian Premier League at Del...",DC,CSK,CSK,BAT FIRST,...,"Prithvi Shaw (UKN),David Warner (UKN),Phil Sal...","Ruturaj Gaikwad (UKN),Devon Conway (UKN),Shiva...","Devon Conway,Ruturaj Gaikwad","Deepak Chahar,Matheesha Pathirana",20 May 2023 - day/night match (20-over match),Chris Gaffaney,Nikhil Patwardhan,Anil Chaudhary,Sanjay Verma,Mohit Krishnadas
4,8,2023.0,1359540,Punjab Kings v Rajasthan Royals,PBKS v RR,"66th Match (N), Indian Premier League at Dhara...",PBKS,RR,RR,BOWL FIRST,...,"Prabhsimran Singh (UKN),Shikhar Dhawan (UKN),A...","Yashasvi Jaiswal (UKN),Jos Buttler (UKN),Devdu...","Devdutt Padikkal,Yashasvi Jaiswal","Navdeep Saini,Adam Zampa",19 May 2023 - night match (20-over match),Nand Kishore,Rod Tucker,Navdeep Singh,Pankaj Dharmani,Parashar Joshi

In [9]:
df.shape

(899, 44)

In [11]:
df.columns

Index(['Unnamed: 0', 'season', 'id', 'name', 'short_name', 'description',
       'home_team', 'away_team', 'toss_won', 'decision', '1st_inning_score',
       '2nd_inning_score', 'winner', 'result', 'start_date', 'end_date',
       'venue_id', 'venue_name', 'home_captain', 'away_captain', 'pom',
       'points', 'super_over', 'home_overs', 'home_runs', 'home_wickets',
       'home_boundaries', 'away_overs', 'away_runs', 'away_wickets',
       'away_boundaries', 'highlights', 'home_key_batsman', 'home_key_bowler',
       'home_playx1', 'away_playx1', 'away_key_batsman', 'away_key_bowler',
       'match_days', 'umpire1', 'umpire2', 'tv_umpire', 'referee',
       'reserve_umpire'],
      dtype='object')

In [13]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 899 entries, 0 to 898
Data columns (total 44 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Unnamed: 0        899 non-null    int64
 1   season            899 non-null    float64
 2   id                899 non-null    int64
 3   name              899 non-null    object
 4   short_name        899 non-null    object
 5   description       899 non-null    object
 6   home_team         899 non-null    object
 7   away_team         899 non-null    object
 8   toss_won          899 non-null    object
 9   decision          899 non-null    object
 10  1st_inning_score  899 non-null    object
 11  2nd_inning_score  899 non-null    object
 12  winner            899 non-null    object
 13  result            899 non-null    object
 14  start_date        899 non-null    object
 15  end_date          899 non-null    object
 16  venue_id          899 non-null    int64
 17  venue_name        899 non-null    object
 18  home_captain      899 non-null    object
 19  away_captain      899 non-null    object
 20  pom               899 non-null    object
 21  points            899 non-null    object
 22  super_over        899 non-null    bool
 23  home_overs        899 non-null    float64
 24  home_runs         899 non-null    float64
 25  home_wickets      899 non-null    float64
 26  home_boundaries   899 non-null    float64
 27  away_overs        899 non-null    float64
 28  away_runs         899 non-null    float64
 29  away_wickets      899 non-null    float64
 30  away_boundaries   899 non-null    float64
 31  highlights        899 non-null    object
 32  home_key_batsman  899 non-null    object
 33  home_key_bowler   899 non-null    object
 34  home_playx1       899 non-null    object
 35  away_playx1       899 non-null    object
 36  away_key_batsman  899 non-null    object
 37  away_key_bowler   899 non-null    object
 38  match_days        899 non-null    object
 39  umpire1           899 non-null    object
 40  umpire2           899 non-null    object
 41  tv_umpire         899 non-null    object
 42  referee           899 non-null    object
 43  reserve_umpire    899 non-null    object
dtypes: bool(1), float64(9), int64(3), object(31)
memory usage: 303.0+ KB

In [11]:
df.describe(include='all')

,Unnamed: 0,season,id,name,short_name,description,home_team,away_team,toss_won,decision,...,home_playx1,away_playx1,away_key_batsman,away_key_bowler,match_days,umpire1,umpire2,tv_umpire,referee,reserve_umpire
count,899.000000,899.000000,8.990000e+02,899,899,899,899,899,899,899,...,899,899,899,899,899,899,899,899,899,899
unique,NaN,NaN,NaN,196,158,899,15,15,15,2,...,883,887,735,796,899,62,64,68,31,69
top,NaN,NaN,NaN,Royal Challengers Bangalore v Kolkata Knight R...,DC v KKR,"70th Match (N), Indian Premier League at Benga...",RCB,MI,MI,BOWL FIRST,...,"Jacques Kallis (AR),Wasim Jaffer (BT),Robin Ut...","Davy Jacobs (WK),Sachin Tendulkar (BT),Ambati ...","Chris Gayle,Virat Kohli","Harshal Patel,Yuzvendra Chahal",21 May 2023 - night match (20-over match),KN Ananthapadmanabhan,Sundaram Ravi,Anil Chaudhary,Javagal Srinath,Krishnamachari Srinivasan
freq,NaN,NaN,NaN,17,21,1,106,114,116,576,...,2,2,8,4,1,62,112,56,163,59
mean,502.519466,2015.729700,8.782062e+05,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
std,293.770827,4.596323,3.501428e+05,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
min,4.000000,2008.000000,3.359820e+05,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25%,244.500000,2012.000000,5.483265e+05,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
50%,508.000000,2015.000000,8.298150e+05,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
75%,754.500000,2020.000000,1.216510e+06,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
max,1028.000000,2023.000000,1.359544e+06,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [17]:
df.isnull().sum()

Unnamed: 0          0
season              0
id                  0
name                0
short_name          0
description         0
home_team           0
away_team           0
toss_won            0
decision            0
1st_inning_score    0
2nd_inning_score    0
winner              0
result              0
start_date          0
end_date            0
venue_id            0
venue_name          0
home_captain        0
away_captain        0
pom                 0
points              0
super_over          0
home_overs          0
home_runs           0
home_wickets        0
home_boundaries     0
away_overs          0
away_runs           0
away_wickets        0
away_boundaries     0
highlights          0
home_key_batsman    0
home_key_bowler     0
home_playx1         0
away_playx1         0
away_key_batsman    0
away_key_bowler     0
match_days          0
umpire1             0
umpire2             0
tv_umpire           0
referee             0
reserve_umpire      0
dtype: int64

In [15]:
df['start_date'].head()

0    2023-05-21T14:00Z
1    2023-05-21T10:00Z
2    2023-05-20T14:00Z
3    2023-05-20T10:00Z
4    2023-05-19T14:00Z
Name: start_date, dtype: object

In [17]:
df['start_date'] = pd.to_datetime(df['start_date'])

df['end_date'] = pd.to_datetime(df['end_date'])

In [19]:
df['start_date'].head()

0   2023-05-21 14:00:00+00:00
1   2023-05-21 10:00:00+00:00
2   2023-05-20 14:00:00+00:00
3   2023-05-20 10:00:00+00:00
4   2023-05-19 14:00:00+00:00
Name: start_date, dtype: datetime64[ns, UTC]

In [21]:
df['run_difference'] = abs(
    df['home_runs'] - df['away_runs']
)

In [25]:
df['toss_match_win'] = (df['toss_won'] == df['winner']).astype(int)

In [31]:
total_matches = len(df)
print("Total matches:",total_matches)

Total matches: 899

#Connecting Python Script to PostgreSQl

In [36]:
!pip install psycopg2-binary sqlalchemy

Requirement already satisfied: psycopg2-binary in c:\users\mpava\anaconda3\lib\site-packages (2.9.12)
Requirement already satisfied: sqlalchemy in c:\users\mpava\anaconda3\lib\site-packages (2.0.30)
Requirement already satisfied: typing-extensions>=4.6.0 in c:\users\mpava\anaconda3\lib\site-packages (from sqlalchemy) (4.11.0)
Requirement already satisfied: greenlet!=0.4.17 in c:\users\mpava\anaconda3\lib\site-packages (from sqlalchemy) (3.0.1)

In [38]:
from sqlalchemy import create_engine

# Step 1: Connect to PostgreSQL
# Replace placeholders with your actual details
username = "postgres"      # default user
password = "Pavani" # the password you set during installation
host = "localhost"         # if running locally
port = "5432"              # default PostgreSQL port
database = "ipl_database"    # the database you created in pgAdmin

engine = create_engine(f"postgresql+psycopg2://{username}:{password}@{host}:{port}/{database}")

# Step 2: Load DataFrame into PostgreSQL
table_name = "matches"   # choose any table name
df.to_sql(table_name, engine, if_exists="replace", index=False)

print(f"Data successfully loaded into table '{table_name}' in database '{database}'.")

Data successfully loaded into table 'matches' in database 'ipl_database'.